#ifndef CONSTANS_H
#define CONSTANS_H

#include "stdbool.h"

#define SCREEN_WIDTH 960
#define SCREEN_HEIGHT 720
#define FRAME_TIME 16666
#define TILE_SIZE 48
#define GRAVITY 1
#define MAX_VERTICAL_SPEED 25
#define PLAYER_JUMP_POWER 25
#define PLAYER_WIDTH 24
#define PLAYER_HEIGHT 24
#define PLAYER_SPEED 4
#define POWER_PLAYER_SPEED 8
#define SLOW_PLAYER_SPEED 2
#define BULLET_HEIGHT 16
#define BULLET_WIDTH 16
#define MAX_PLAYERS 2
#define SPAWN_A 816
#define SPAWN_B 48
#define CLIENT_FRAME_TIME 15
#define SERVER_FRAME_TIME 15
#define X_AXIS 1
#define Y_AXIS 0
#define BUF_MAX 256
#define SPAWN_X 48
#define SPAWN_Y 624
#define LEFT_KEY 0x01
#define RIGHT_KEY 0x02
#define UP_KEY 0x04
#define DOWN_KEY 0x08
#define ATTACK_KEY 0x10
#define POWERA_KEY 0x20
#define POWERUPA_APPLY_TIME 150
#define POWERUPB_APPLY_TIME 150
#define POWERUPC_APPLY_TIME 300
#define WAIT_FRAME 6
#define POWERUP_WIDTH 24
#define POWERUP_HEIGHT 24
#define POWERUP_SPAWNTIME 3000
#define MAX_POWERUP 8

#endif
